owner: EthernovaDev
repo: status

sites:
  - name: Website
    url: https://ethnova.net
  - name: Mining Pool
    url: https://pool.ethnova.net
  - name: Explorer
    url: https://explorer.ethnova.net
  - name: Public RPC
    url: https://rpc.ethnova.net
    method: POST
    headers:
      - "Content-Type: application/json"
    body: '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'
    expectedStatusCodes:
      - 200
  - name: Stats API
    url: https://api.ethnova.net/stats.json
    expectedStatusCodes:
      - 200

status-website:
  baseUrl: /status
  theme: night
  name: Ethernova Status
  introTitle: "Ethernova Network Status"
  introMessage: "Fast, clear uptime and latency for Ethernova RPC, Explorer, and Mining Pool."
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://ethnova.net
    - title: Explorer
      href: https://explorer.ethnova.net
    - title: RPC
      href: https://rpc.ethnova.net
    - title: Pool
      href: https://pool.ethnova.net
    - title: Stats
      href: https://api.ethnova.net/stats.json
